# Generated by Django 4.2.10 on 2024-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_albumartistrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='app.artist'),
        ),
        migrations.DeleteModel(
            name='AlbumArtistRelationship',
        ),
    ]
