# Generated by Django 4.2.10 on 2024-04-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='follows',
            field=models.ManyToManyField(to='app.person'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.CreateModel(
            name='UserAlbumRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.artist'),
            preserve_default=False,
        ),
    ]
