# Generated by Django 4.2.10 on 2024-04-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_person_follows_remove_album_artist_useralbumrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralbumrating',
            name='album',
        ),
        migrations.RemoveField(
            model_name='useralbumrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='UserAlbumRating',
        ),
    ]
