# Generated by Django 4.2.10 on 2024-04-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_useralbumrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useralbumrating',
            old_name='user',
            new_name='userOwner',
        ),
    ]
