# Generated by Django 4.2.10 on 2024-04-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_user_useralbumrating_userowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbumrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
