# Generated by Django 4.2.10 on 2024-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='favoriteColor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='follows',
            field=models.ManyToManyField(blank=True, to='users.person'),
        ),
    ]
